name: flutter_studioghibliapp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  shared_preferences: ^2.0.15
  flutter_native_splash: ^2.2.3
  font_awesome_flutter: ^10.1.0
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.png
  color_dark: "#121212"
  image_dark: assets/splash_dark.png

flutter:
  uses-material-design: true
